# Generated by Django 3.1.2 on 2020-11-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_shipping_fee', models.CharField(max_length=100)),
                ('where_to_send', models.CharField(max_length=100)),
                ('detail_information', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'maincategories',
            },
        ),
        migrations.CreateModel(
            name='MoreInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_status', models.CharField(max_length=100)),
                ('receipt', models.CharField(max_length=100)),
                ('business_classification', models.CharField(max_length=100)),
                ('producer_importer', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('manufacturing_date', models.CharField(max_length=100)),
                ('shelf_life', models.CharField(max_length=100)),
                ('storage_method', models.CharField(max_length=100)),
                ('delivery_period', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
            ],
            options={
                'db_table': 'productgroups',
            },
        ),
        migrations.CreateModel(
            name='SellerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.CharField(max_length=100)),
                ('business_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'subsubcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=80, null=True)),
                ('thumbnail_image', models.URLField(max_length=500)),
                ('detail_image', models.URLField(max_length=500)),
                ('essential', models.BooleanField()),
                ('optional', models.BooleanField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('buy_count', models.ManyToManyField(related_name='buy_product', through='order.OrderItem', to='order.Order')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.exchange')),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.maincategory')),
                ('more_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.moreinformation')),
                ('productgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productgroup')),
                ('seller_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sellerinformation')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
                ('subsubcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subsubcategory')),
                ('watchlist', models.ManyToManyField(related_name='watch_product', to='user.User')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
