# Generated by Django 3.1.2 on 2020-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productgroup_id',
            new_name='productgroup',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subsubcategy_id',
            new_name='subsubcategy',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='maincategory_id',
            new_name='maincategory',
        ),
        migrations.RenameField(
            model_name='subsubcategory',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='PhotoReview',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
