# Generated by Django 3.1.2 on 2020-11-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201118_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='essencial',
        ),
        migrations.RemoveField(
            model_name='product',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='product',
            name='more_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='optional',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productgroup',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subsubcategy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='watch_count',
        ),
    ]
