# Generated by Django 3.1.2 on 2020-11-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0002_auto_20201118_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='watch_count',
        ),
        migrations.AddField(
            model_name='product',
            name='watchlist',
            field=models.ManyToManyField(null=True, related_name='watch_product', to='user.User'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
