# Generated by Django 3.1.2 on 2020-11-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201118_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='essencial',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subsubcategy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='watch_count',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='maincategory',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='essential',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='maincategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.maincategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subsubcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='optional',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productgroup'),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brands',
        ),
    ]
