# Generated by Django 3.1.2 on 2020-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0003_auto_20201122_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_count',
            field=models.ManyToManyField(null=True, related_name='buy_product', to='user.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='watchlist',
            field=models.ManyToManyField(null=True, related_name='watch_product', to='user.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exchange',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='more_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_information',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
