# Generated by Django 3.1.2 on 2020-11-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201121_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='maincategory',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='SubSubCategory',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
