# Generated by Django 3.1.2 on 2020-11-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201119_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subsubcategy',
            new_name='subsubcategory',
        ),
    ]
