# Generated by Django 3.1.2 on 2020-11-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_checkid'),
        ('product', '0004_auto_20201121_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
            ],
            options={
                'db_table': 'maincategories',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
            ],
            options={
                'db_table': 'productgroups',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.maincategory')),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='buy_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='essencial',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='exchange',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='more_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='optional',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='watch_count',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'watchlists',
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
            options={
                'db_table': 'subsubcategories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='productgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='subsubcategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subsubcategory'),
        ),
    ]
