# Generated by Django 3.1.2 on 2020-11-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201119_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='maincategory',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='maincategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.maincategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
