# Generated by Django 3.1.2 on 2020-11-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_checkid'),
        ('product', '0005_auto_20201123_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='essencial',
            new_name='essential',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subsubcategy',
            new_name='subsubcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='watch_count',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='maincategory',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='maincategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.maincategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='watchlist',
            field=models.ManyToManyField(related_name='watch_product', to='user.User'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_count',
        ),
        migrations.AddField(
            model_name='product',
            name='buy_count',
            field=models.ManyToManyField(related_name='buy_product', to='user.User'),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
