# Generated by Django 3.1.2 on 2020-11-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201123_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_shipping_fee', models.CharField(max_length=100)),
                ('where_to_send', models.CharField(max_length=100)),
                ('detail_information', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MoreInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_status', models.CharField(max_length=100)),
                ('receipt', models.CharField(max_length=100)),
                ('business_classification', models.CharField(max_length=100)),
                ('producer_importer', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('manufacturing_date', models.CharField(max_length=100)),
                ('shelf_life', models.CharField(max_length=100)),
                ('storage_method', models.CharField(max_length=100)),
                ('delivery_period', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SellerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.CharField(max_length=100)),
                ('business_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.exchange'),
        ),
        migrations.AlterField(
            model_name='product',
            name='more_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.moreinformation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sellerinformation'),
        ),
    ]
