# Generated by Django 3.1.2 on 2020-11-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'answer_statuses',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'question_types',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.answerstatus'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.questiontype'),
        ),
    ]
