# Generated by Django 3.1.2 on 2020-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_status',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
