# Generated by Django 3.1.2 on 2020-11-21 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20201120_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'question_types',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.question_type'),
        ),
    ]
