# Generated by Django 3.1.2 on 2020-11-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20201121_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'answer_statuses',
            },
        ),
    ]
