# Generated by Django 3.1.2 on 2020-11-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_answer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.answer_status'),
        ),
    ]
