# Generated by Django 3.1.2 on 2020-11-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20201121_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_status',
            new_name='AnswerStatus',
        ),
        migrations.RenameModel(
            old_name='Question_type',
            new_name='QuestionType',
        ),
    ]
