# Generated by Django 3.1.2 on 2020-11-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201119_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckId',
        ),
    ]
