# Generated by Django 3.1.2 on 2020-11-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_checkid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_code', models.CharField(max_length=30)),
            ],
        ),
    ]
