# Generated by Django 3.1.2 on 2020-11-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_allow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allow',
            table='allows',
        ),
    ]
