# Generated by Django 3.1.2 on 2020-11-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201122_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
